FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf

COPY frontend/web-pages /usr/share/nginx/html

COPY logos /usr/share/nginx/html/files/logos

COPY test_pictures /usr/share/nginx/html/files/test_pictures

EXPOSE 80