name: Lint Frontend

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install ESLint
        run: npm install --save-dev eslint @eslint/js

      - name: Run ESLint
        run: |
          npx eslint nginx/frontend/**/*.js \
            --env browser \
            --env es2022 \
            --parser-options=sourceType:module,ecmaVersion:2022 \
            --rule "no-unused-vars: warn" \
            --rule "no-undef: error"
